### ISSUE TITLE
How to make wv_one_second_rect_size edit work correctly ?

### ISSUE THREAD

**Issue by DevTrinh** [SheTieJun/AudioWaveView#1]
Why does the wv_one_second_rect_size parameter always have to be 25? If I put it smaller, it doesn't work correctly. What's the cause here? How can I fix it?

**Comment by SheTieJun** [comment]
It need to be used with specific recording callbacks.
My DEMO example: one data = 40ms recording = one Frame rectangle, so 25*40 = 1000ms = 1S.
So if you want to change to more than 25, then you need a smaller block of recording data, such as 50, then 1000/50 = 20ms, one data of your recording callback must be 20ms, and `addFrame ` is called every 20ms.
`wv_one_second_rect_size`: The number of Frame rectangles for one second of recording data, the default is 25.
