### ISSUE TITLE
打扰一下，请问这里获取到volume 转换的算法是根据什么来的?

### ISSUE THREAD

**Issue by kwg520** [SheTieJun/AudioWaveView#2]
<img width="1034" alt="image" src="https://github.com/user-attachments/assets/99eb7c21-275f-479a-93a2-5ea7fba0be40" />
```
fun getVoiceLevel(it: Int): Float {
        val currentLevel = when {
            it <= 0 -> 0.8f
            it < 20 -> (0.5f) + (it - 20) / 10f
            it in 20..30 -> (0.8f) + (it - 20) / 10f
            it in 40..55 -> (1.0f) + (it - 40) / 15f
            it in 55..58 -> (1.2f) + (it - 55) / 3f
            it in 58..60 -> (2.2f) + (it - 58) / 2f
            it in 60..62 -> (3.3f) + (it - 60) / 2f
            it in 62..65 -> (4.6f) + (it - 62) / 3f
            it in 65..68 -> (5.9f) + (it - 65) / 3f
            it in 68..70 -> (7.1f) + (it - 68) / 3f
            it in 70..75 -> (8.5f) + (it - 70) / 5f
            it in 75..80 -> (11f) + (it - 75) / 5f
            else -> 13.5f
        }
        return currentLevel
    }
```
我这里看你用的TestWaveViewActivity里面 mViewBinding.audioWaveView.addFrame((1..9).random().toFloat(), duration)，这里1-9绘制出来的是挺好看的，但是MainActivity用上面getVoiceLevel算出来的都是1.0到13.5f，不应该固定在1到9的区间吗？想了解下

**Comment by SheTieJun** [comment]
额，当时这样只是为了好看一点而已，不用纠结。这只是一个 UI 库，不要把 demo 中特殊写法 想太多。

**Comment by SheTieJun** [comment]
我想把低音和高音区别大一点，但是不太理想

**Comment by SheTieJun** [comment]
问题：不应该固定在1到9的区间吗？想了解下
 - 1-9  是因为我把 wv_rect_level  = 10
 - 1.0到13.5f 是因为我吧 wv_rect_level="15"

**Comment by kwg520** [comment]
<img width="838" alt="image" src="https://github.com/user-attachments/assets/fcca7587-716e-4f82-8772-6d72727cbb87" />
这个是实际的volume，如果我现在就是wv_rect_level="15"，有没有比较好的均匀一点的算法，绘制这个如何好看点呢

**Comment by SheTieJun** [comment]
暂时没有， 主要是声音本身就是不规则的，我也尝试想把他规则化美化，但是实验效果很差~ 抱歉，能力有限

**Comment by kwg520** [comment]
打扰了，我这里找到了个，https://github.com/SimpleMobileTools/Simple-Voice-Recorder ，这个里面的Mp3Recorder 这个类算出来的amplitude ，区别是一个算的是平均，在另一个可视化的view挺好看，把它映射到1-13f的范围是不是更好看，你参考下private fun updateAmplitude(data: ShortArray) {
        var sum = 0L
        for (i in 0 until minBufferSize step 2) {
            sum += abs(data[i].toInt())
        }
        amplitude.set((sum / (minBufferSize / 8)).toInt())
    }和    private int getDb(byte[] data) {
        double sum = 0;
        double ave;
        int length = Math.min(data.length, 128);
        int offsetStart = 0;
        for (int i = offsetStart; i < length; i++) {
            sum += data[i] * data[i];
        }
        ave = sum / (length - offsetStart);
        return (int) (Math.log10(ave) * 20);
    }   结论 updateAmplitude 更适合实时绘制音频幅度。
getDb 更适合音量强度或噪音级别分析。
如果需要同时支持两者，可以在音频数据读取时统一处理成 ShortArray 或 byte[]，避免数据转换开销。

**Comment by SheTieJun** [comment]
OK，后面我会试试，我demo录音工具是支持PCM ShortArray 数据~
